### ISSUE TITLE
回去等通知吧！

### ISSUE THREAD

**Issue by AKmro** [yifeikong/reverse-interview-zh#33]
技术面试到最后，面试官说句“你有什么问题需要问我的”？大部分是客套话，无非走个流程，你问不问也没啥卵用，出门这辈子估计跟这公司里的人没有任何交际，真要招你，已经迫不及待叫HR来跟你谈最终面。

**Comment by yifeikong** [comment]
不知道您是怎么做的，我一般会在不泄密的前提下尽量真实回答候选人的问题。

诚然，问不问一般不会影响面试结果。但是一般候选人向提问面试官也不是为了改变面试结果吧，而是为了了解公司的一些信息，为自己下一份工作做出更好的决策。可能您对提问目的理解和大多数人有一些偏差。
